### ISSUE TITLE
Update Github Action

### ISSUE THREAD

**Issue by mathielen** [FriendsOfCXML/cxml-php#11]
Hi @ynnoig ,

could you pls update the Github Action so that the deprecation errors are gone?

- `Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/cache@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-act`
- `The save-state command is deprecated and will be disabled soon.`
- `The set-output command is deprecated and will be disabled soon.`

BG

**Comment by ynnoig** [comment]
Of course. I will make today. Thank u for the Feedback.
