### ISSUE TITLE
Could not parse date

### ISSUE THREAD

**Issue by nickworks** [FriendsOfCXML/cxml-php#15]
My cXML endpoint was working correctly, but now the messages being sent from a client are throwing errors! Specifically, `Could not parse date: 2023-04-20T19:23:18`

- When the cXML timestamp is formatted like `2023-04-20T01:35:38+00:00` the messages are parsed successfully. 
- When the cXML timestamp is formatted like `2023-04-20T19:23:18` parsing fails and I cannot receive the message.

Here's what an example message looks like:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE cXML SYSTEM "http://xml.cxml.org/schemas/cXML/1.2.007/cXML.dtd">
<cXML  version="1.2.007" payloadID="20230420.192318392.TEST.NHA100026096.1693-1" timestamp="2023-04-20T19:23:18">
    <Header>
      <From>
         <Credential domain="DUNS">
            <Identity>12345678</Identity>
         </Credential>
      </From>
      <To>
         <Credential domain="DUNS">
            <Identity>12345678</Identity>
         </Credential>
      </To>
      <Sender>
         <Credential domain="OracleSN">
            <Identity>testexchange.oracle.com</Identity>
            <SharedSecret>punch0ut-password!</SharedSecret>
         </Credential>
         <UserAgent>Oracle Supplier Network</UserAgent>
      </Sender>
    </Header>
    <Request>
        <ProfileRequest />
    </Request>
</cXML>
```

Is there a solution? Thank you.

**Comment by ynnoig** [comment]
According to the official cXML documentation, the "timestamp" attribute is defined as follows:

The date and time the message was sent, in ISO 8601 format. This value should not
change for retry attempts.
The format is YYYY-MM-DDThh:mm:ss-hh:mm (for example,
2015-07-14T19:20:30+01:00).

https://xml.cxml.org/current/cXMLReferenceGuide.pdf (Page 25).

Given the previous statement I think it is appropriate to close this issue and not classify it as a bug.
