### ISSUE TITLE
How to use the Builder?

### ISSUE THREAD

**Issue by klynicol** [FriendsOfCXML/cxml-php#16]
Hello!

I'm attempting to build a response via the Builder but it seems like some of the Payload Interfaces are unfinished. I would expect something like this to add xml attributes?

```
class MyMessage implements MessagePayloadInterface
{
	public $SomeProperty;
}
$messagePayloadInterface = new MyMessage();
$messagePayloadInterface->SomeProperty = 'SomeValue';
$payload = new \CXml\Model\Message\Message($messagePayloadInterface, $status, $id, $deploymentMode, $inReplyTo);
$cXml = \CXml\Builder::create()
	->payload($payload)
	->from(...)
	->to(...)
	->sender(...)
	->build();
```

I guess I'm not exactly sure of how to use the Builder. Do you have examples or further documentation on it?

Thank you very much

**Comment by mathielen** [comment]
Hi there,

yes it's definitely not feature-complete. I did not need all the messages from the cxml-universe (yet).
You are free to extend the framework as you like :)

Best regards
Markus
