### ISSUE TITLE
add Phone and children

### ISSUE THREAD

**Issue by isybuy** [FriendsOfCXML/cxml-php#25]
Hello, I'm using your library for my project and the Phone in the Address class doesn't conform to CXml practice, you're sending a string when we need more fields (according to https://xml.cxml.org/current/cXMLReferenceGuide.pdf)
```xml
<Phone name="work">
    <TelephoneNumber>
        <CountryCode isoCountryCode="BE" />
        <AreaOrCityCode />
        <Number>1151869655</Number>
    </TelephoneNumber>
</Phone>
 ```
 Can you add it please ? 😎

**Comment by mathielen** [comment]
Hey there!

You're welcome to add a PR with the changes you propose. Happy to merge it :)
